import { Montserrat} from "next/font/google";
import "./globals.css";
import MenuBar from "@/components/MenuBar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],});

export const metadata = {
  title: "Tech Design",
  description: "Generated by create next app",
  
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
       <MenuBar/>
        {children}
        <div className="warning">
           Please use a smaller screen to view this website
         </div>
        
      </body>
    </html>
  );
}
